name: build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ github.token }}
        submodules: true

    - uses: actions/upload-artifact@v3
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
      with:
        name: package
        path: |
          concepts
          *.meta.yaml

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: package

    - name: Display structure of downloaded files
      run: ls -R

    - name: Compress files
      run: zip -9 -r package.zip ./*

    - name: Upload release
      id: upload-release-asset
      uses: softprops/action-gh-release@v1
      with:
        body: Automatic release of ${{ github.ref }}
        files: |
          package.zip
